openapi: 3.0.4
info:
  title: CrowdProj
  description: An experimental project with high modularity
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.0

paths:
  /x:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/X'

components:
  schemas:

    X:
      $ref: './build/base.yaml#/components/schemas/CpRequestDebug'

    Y:
      type: string
